spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://${myip}/sell?characterEncoding=utf-8&useSSL=false
  jackson:
    default-property-inclusion: non_null    #配置null不显示
  redis:
    host: 10.10.86.130
    port: 6379


myip: 10.10.86.130
server:
    context-path: /sell
wechat:
  mpAppId: wx7dc00669e20b4f7e
  mpAppSecret: 78721bdc7e63ef7a21e675d8be4685de
  mchKey: 123
  mchId: 123
  keyPath: 123    #下载下来的
  notifyUrl: 123
  openAppId: wxf70f7ee85e71e48d
  openAppSecret: e69b86ce5b11cd824dfdb34a62d498e0
  templateId:
    orderStatus: 123456

projecturl:
  wechatMpAuthorize: http://985qpe.natappfree.cc #域名
  wechatOpenAuthorize: http://985qpe.natappfree.cc
  sell: http://985qpe.natappfree.cc

