spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://${myip}/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null    #配置null不显示
myip: 10.10.86.130
server:
  servlet:
    context-path: /sell
wechat:
  mpAppId: 123
  mpAppSecret: 123

projecturl:
  wechatMpAuthorize: 123 #域名



