spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://${myip}/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null    #配置null不显示



myip: 10.10.86.130
server:
    context-path: /sell
wechat:
  mpAppId: wx7dc00669e20b4f7e
  mpAppSecret: 78721bdc7e63ef7a21e675d8be4685de
  mchKey: 123
  mchId: 123
  keyPath: 123    #下载下来的
  notifyUrl: 123



projecturl:
  wechatMpAuthorize: http://n53q4m.natappfree.cc #域名



